NBAPex/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^nba_stats/', include('nba_stats.urls', namespace='nba_stats')),
    url(r'^nba_fantasy/', include('nba_fantasy.urls', namespace='nba_fantasy')),
]

nba_fantasy/urls.py
from django.conf.urls import url
from nba_fantasy import views, ajax_views, class_views

urlpatterns = [url(r'^$', class_views.IndexView.as_view(), name='index'),
               url(r'^login/$', views.login, name='login'),
               url(r'^create_league/$', class_views.FantasyLeagueFormView.as_view(),
                   name="create-league"),
               url(r'^league_homepage/(?P<league_id>[0-9]+)$', views.league_homepage,
                   name='league-homepage'),
               url(r'^edit_team/(?P<league_id>[0-9]+)$', views.create_team,
                   name='create-team'),
               url(r'^edit_team/(?P<league_id>[0-9]+)/(?P<team_id>[0-9]+)$', views.edit_team,
                   name='edit-team'),
               url(r'^view_team/(?P<team_id>[0-9]+)/$', views.view_team,
                   name='view-team'),
               url(r'^view_team/(?P<team_id>[0-9]+)/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/$',
                   views.view_team, name='view-team-date'),
               url(r'^draft/(?P<league_id>[0-9]+)$', views.draft,
                   name='draft'),
               url(r'^free_agents/(?P<league_id>[0-9]+)$', views.free_agents,
                   name='free-agents'),
               url(r'^trade/(?P<league_id>[0-9]+)$', views.trade,
                   name='trade'),
               url(r'^accept_trade/(?P<transaction_id>[0-9]+)$', views.accept_trade,
                   name='accept-trade'),
               url(r'^schedule/(?P<league_id>[0-9]+)$', views.schedule,
                   name='schedule'),
               url(r'^matchup/(?P<matchup_id>[0-9]+)$', views.matchup,
                   name='matchup'),
               url(r'^standings/(?P<league_id>[0-9]+)$', views.standings,
                   name='standings'),
               url(r'^ajax/add_free_agent/$', views.add_free_agent, name='add-free-agent'),
               url(r'^ajax/propose_trade/$', views.propose_trade, name='propose-trade'),
               url(r'^ajax/update_fantasy_lineup', ajax_views.ajax_update_fantasy_lineup,
                   name='ajax-update-fantasy-lineup')
               ]

nba_fantasy/views.py
import json
import logging
from datetime import date, datetime

from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from nba_fantasy.helpers.matchup import TeamMatchupEntries
from nba_fantasy.helpers.team import create_lineup_entry_rows
from nba_fantasy.forms import (FantasyLeagueForm, FantasyTeamForm, LoginForm)
from nba_fantasy.helpers.transaction import (create_trade_proposal, handle_accepted_trade,
                                             add_free_agent_to_team)
from nba_fantasy.models import (FantasyLeague, FantasyTeam, FantasyTeamRosterEntry,
                                FantasyTeamTransaction, FantasyMatchup, FantasyLineupEntry)
from nba_stats.models import Player
from nba_stats.helpers.split import SPLIT_FIELD_ORDERING

log = logging.getLogger('fantasy')


def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user_data = form.cleaned_data
            user = authenticate(username=user_data['username'],
                                password=user_data['password'])
            if user is not None:
                request.session['user_id'] = user.id
            else:
                # TODO: Handle this properly
                request.session['user_id'] = -1

            return redirect("nba_fantasy:index")
    else:
        form = LoginForm()

    context = {'form': form}
    return render(request, "nba_fantasy/login.html", context)


def create_league(request):
    if request.method == "POST":
        form = FantasyLeagueForm(request.POST)
        if form.is_valid():
            league = form.save()
            return redirect("nba_fantasy:roster-settings", league_id=league.id)
    else:
        form = FantasyLeagueForm()

    context = {'form': form}
    return render(request, "nba_fantasy/create_league.html", context)


def league_homepage(request, league_id):
    league = FantasyLeague.objects.get(id=league_id)
    team = FantasyTeam.objects.filter(league=league,
                                      owner_id=request.session['user_id']).first()
    context = {'league': league, 'team_id': team.id or 0}
    log.debug(("session user", request.session['user_id']))
    return render(request, "nba_fantasy/league_homepage.html", context)


def create_team(request, league_id):
    league = FantasyLeague.objects.get(id=league_id)
    if request.method == "POST":
        form = FantasyTeamForm(request.POST)
        if form.is_valid():
            owner = User.objects.get(id=request.session['user_id'])
            team = form.save(commit=False)
            team.owner = owner
            team.league = league
            team.win_pct = 0
            team.save()
            return redirect("nba_fantasy:league-homepage", league_id=league.id)
    else:
        form = FantasyTeamForm()

    context = {'league': league, 'form': form, 'action': 'create'}
    return render(request, "nba_fantasy/create_team.html", context)


def edit_team(request, league_id, team_id):
    league = FantasyLeague.objects.get(id=league_id)
    fantasy_team = FantasyTeam.objects.get(id=team_id)

    if request.method == "POST":
        form = FantasyTeamForm(request.POST, instance=fantasy_team)
        if form.is_valid():
            team = form.save(commit=False)
            team.league = league
            team.save()
            return redirect("nba_fantasy:league-homepage", league_id=league.id)
    else:
        form = FantasyTeamForm(instance=fantasy_team)

    context = {'league': league, 'form': form, 'action': 'edit',
               'team': fantasy_team}
    return render(request, "nba_fantasy/edit_team.html", context)


def view_team(request, team_id, year=None, month=None, day=None):
    log.debug(("FOX", int(team_id)))
    log.debug(("ELEPHANT", int(team_id) == 0))
    if int(team_id) == 0:
        log.debug("IN HERE")
        return redirect("nba_fantasy:create-team", league_id=request.session['league_id'])

    team = FantasyTeam.objects.get(id=team_id)
    score_settings = team.league.scoringsettings
    score_fields = sorted([f for f in score_settings.scoring_fields_vals],
                          key=SPLIT_FIELD_ORDERING.index)
    pending_trades = FantasyTeamTransaction.objects.filter(team=team,
                                                           expiry_time__gt=datetime.now(),
                                                           accepted_flag=False)

    if year is None and month is None and day is None:
        lup_date = date.today()
    else:
        lup_date = date(year=int(year),
                        month=int(month),
                        day=int(day))

    default_date_str = lup_date.strftime("%m/%d/%Y")
    lineup_entries = create_lineup_entry_rows(team,
                                              scoring_settings=score_settings,
                                              lineup_date=lup_date)
    context = {'team': team, 'league': team.league, 'pending_trades': pending_trades,
               'lineup_entries': lineup_entries, 'default_date_str': default_date_str,
               'score_fields': score_fields}
    return render(request, "nba_fantasy/view_team.html", context)


def draft(request, league_id):
    league = FantasyLeague.objects.get(id=league_id)
    user = User.objects.get(id=request.session['user_id'])
    ros_entries = FantasyTeamRosterEntry.objects.filter(league=league,
                                                        team=None,
                                                        end_date=None,
                                                        acquired_via="UO").values_list('player_id',
                                                                                       flat=True)
    available_players = Player.objects.filter(id__in=ros_entries)
    # Temp

    team = FantasyTeam.objects.get(league=league,
                                   owner=user)
    context = {'league': league, 'available_players': available_players, 'team': team}
    return render(request, "nba_fantasy/draft.html", context)


def free_agents(request, league_id):
    league = FantasyLeague.objects.get(id=league_id)
    user = User.objects.get(id=request.session['user_id'])
    team = FantasyTeam.objects.get(league=league,
                                   owner=user)
    ros_entries = FantasyTeamRosterEntry.objects.filter(league=league,
                                                        team=None,
                                                        end_date=None).values_list('player_id',
                                                                                   flat=True)
    fa_players = Player.objects.filter(id__in=ros_entries)
    context = {'league': league, 'fa_players': fa_players, 'team': team}
    return render(request, "nba_fantasy/free_agents.html", context)


def trade(request, league_id):
    league = FantasyLeague.objects.get(id=league_id)
    user = User.objects.get(id=request.session['user_id'])
    team = FantasyTeam.objects.get(league=league,
                                   owner=user)
    other_teams = FantasyTeam.objects.filter(league=league).exclude(owner=user)
    context = {'league': league, 'user': user,
               'team': team, 'other_teams': other_teams}
    return render(request, 'nba_fantasy/trade.html', context)


def accept_trade(request, transaction_id):
    myteam_trade = FantasyTeamTransaction.objects.get(id=transaction_id)
    all_related_trades = FantasyTeamTransaction.objects.filter(trade_identifier=
                                                               myteam_trade.trade_identifier)
    handle_accepted_trade(all_related_trades)
    context = {}
    return render(request, 'nba_fantasy/accept_trade.html', context)


def schedule(request, league_id):
    league = FantasyLeague.objects.get(id=league_id)
    team = FantasyTeam.objects.get(league=league,
                                   owner_id=request.session['user_id'])
    cur_week = (date.today() - league.season_start_date).days // 7
    # Temp for testing
    cur_week = 15
    context = {'league': league, 'team': team, 'cur_week': cur_week}
    weeks = range(league.start_week, (league.reg_season_matchups *
                                           league.weeks_per_matchup))
    context['weeks'] = []

    matchups = FantasyMatchup.objects.filter(home_team__league=league)
    for week in weeks:
        context['weeks'].append(matchups.filter(week_num=week))
    context['matchups'] = matchups

    return render(request, 'nba_fantasy/schedule.html', context)


def matchup(request, matchup_id):
    mup = FantasyMatchup.objects.get(id=matchup_id)
    mup.score_matchup()
    league = mup.home_team.league
    log.debug(("NARWHAL", SPLIT_FIELD_ORDERING))
    scoring_fields = sorted(league.scoringsettings.scoring_fields_vals.keys(),
                            key=SPLIT_FIELD_ORDERING.index)
    scoring_fields.append("total")
    display_fields = [s.split("__")[-1].upper().replace("_", " ") for s in scoring_fields]
    my_team = FantasyTeam.objects.get(league=league,
                                      owner=request.session['user_id'])

    home_entries = TeamMatchupEntries(matchup=mup,
                                      team=mup.home_team)
    home_rows = home_entries.create_rows()
    log.debug(("HOME ROWS", [(h.player_name, h.score_fields) for h in home_rows]))

    away_entries = TeamMatchupEntries(matchup=mup,
                                      team=mup.away_team)
    away_rows = away_entries.create_rows()
    log.debug(("AWAY ROWS", [(h.player_name, h.score_fields) for h in away_rows]))

    context = {'league': league, 'team': my_team, 'matchup': mup,
               'home_rows': home_rows, 'away_rows': away_rows,
               'scoring_fields': scoring_fields, 'display_fields': display_fields}

nba_fantasy/templates/nba_fantasy/create_league.html
{% extends "nba_stats/base.html" %}

{% block title %} NBAPex Fantasy Basketball {% endblock %}
{% block content %}

<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <form action="{% url 'nba_fantasy:create-league' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" value="Create League"/>
            </form>
        </div><!-- /input-group -->
    </div>
</div>

{% endblock %}

nba_fantasy/templates/nba_fantasy/create_league_single_page.html
{% extends "nba_stats/base.html" %}

{% block title %}NBAPex | Create Fantasy League {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#league">Basic Settings</button>
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#transaction">Transactions</button>
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#schedule">Schedule</button>
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#draft">Draft</button>
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#scoring">Scoring</button>
                <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#roster">Roster</button>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-6">
            <div class="input-group">
                <form name="create_league_form" action="{% url 'nba_fantasy:create-league' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div id="league" class="panel panel-default collapse">
                        <div class="panel-heading">
                            <h3 class="panel-title">Basic</h3>
                        </div>
                        <div class="panel-body">
                            {{ form.as_p }}
                        </div>
                    </div>
                    <div id="transaction" class="panel panel-default collapse">
                        <div class="panel-heading">
                            <h3 class="panel-title">Transaction</h3>
                        </div>
                        <div class="panel-body">
                            {{ transaction.as_p }}
                        </div>
                    </div>
                    <div id="schedule" class="panel panel-default collapse">
                        <div class="panel-heading">
                            <h3 class="panel-title">Schedule</h3>
                        </div>
                        <div class="panel-body">
                            {{ schedule.as_p }}
                        </div>
                    </div>
                    <div id="draft" class="panel panel-default collapse">
                        <div class="panel-heading">
                            <h3 class="panel-title">Draft</h3>
                        </div>
                        <div class="panel-body">
                            {{ draft.as_p }}
                        </div>
                    </div>
                    <div id="scoring" class="panel panel-default collapse">
                        <div class="panel-heading">
                            <h3 class="panel-title">Scoring</h3>
                        </div>
                        <div class="panel-body">
                            {{ scoring_options.as_p }}
                            <div class="btn-group" role="group" aria-label="...">
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#traditional">Traditional</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#advanced">Advanced</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#misc">Misc</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#scoring">Scoring</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#usage">Usage</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#tracking">Tracking</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#four_factors">Four Factors</button>
                              <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#hustle">Hustle</button>
                            </div>
                            <div id="traditional" class="collapse">
                                <h4>Traditional</h4>
                                {{ traditional.as_p }}
                            </div>
                            <div id="advanced" class="collapse">
                                <h4>Advanced</h4>
                                {{ advanced.as_p }}
                            </div>
                            <div id="misc" class="collapse">
                                <h4>Misc</h4>
                                {{ misc.as_p }}
                            </div>
                            <div id="scoring" class="collapse">
                                <h4>Scoring</h4>
                                {{ scoring.as_p }}
                            </div>
                            <div id="usage" class="collapse">
                                <h4>Usage</h4>
                                {{ usage.as_p }}
                            </div>
                            <div id="tracking" class="collapse">
                                <h4>Tracking</h4>
                                {{ tracking.as_p }}
                            </div>
                            <div id="four_factors" class="collapse">
                                <h4>Four Factors</h4>
                                {{ four_factors.as_p }}
                            </div>
                            <div id="hustle" class="collapse">
                                <h4>Hustle Stats</h4>
                                {{ hustle.as_p }}
                            </div>
                        </div>
                    </div>
                    <div id="roster" class="panel panel-default collapse">
                        <div class="panel-heading">
                            <h3 class="panel-title">Roster</h3>
                        </div>
                        <div class="panel-body">
                            {{ roster.as_p }}
                        </div>
                    </div>
                    <input type="submit" value="Create League"/>
                </form>
            </div><!-- /input-group -->
        </div>
    </div>
{% endblock %}

nba_fantasy/templates/nba_fantasy/draft.html
{% extends "nba_stats/base.html" %}
{% block title %} {{ league.name }} Draft{% endblock %}
{% block content %}

Draft<br>
{{ league.name }}<br>
{{ team.owner.username }}<br>

<button type="button" class="btn btn-default" id="draft_player">Draft Player</button>
<table id="avail_players_table" class="table table-striped">
    <thead>
        <tr>
            <th>Player</th>
        </tr>
    </thead>
    <tbody>
        {% for player in available_players %}
            <tr id="{{player.id}}_player_row">
                <td>{{ player.display_first_last }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block javascript %}
    <script>
        $(function(){
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/nba_fantasy/draft/{{ team.owner.id }}/{{ league.id }}";
            console.log("Connecting to " + ws_path);
            var socket = new WebSocket(ws_path);
            socket.onmessage = function(message){
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                if (data.drafted){
                    var selected = $("#" + data.selected);
                    selected.remove();
                    alert("Drafted player!");
                }
            };
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            };
            $("#avail_players_table tr").click(function(){
                $(this).addClass('selected').siblings().removeClass('selected');
                $(this).addClass('info').siblings().removeClass('info');
                console.log("Selected");
                console.log($(this));
            });
            $("#draft_player").click(function (e) {
                console.log("Button clicked!");
                var selected = $("#avail_players_table tr.selected");
                console.log(selected);
                var player_id = parseInt(selected.attr("id").replace("_player_row", ""));
                console.log(player_id);
                 socket.send(JSON.stringify({
                        "team_id": {{ team.id }},
                        "player_id": player_id
                    }));
            })
        });
    </script>
{% endblock %}

nba_fantasy/templates/nba_fantasy/draft_settings.html
{% extends "nba_stats/base.html" %}
{% block title %} {{ league.name }} Draft Settings {% endblock %}
{% block content %}

Draft Settings<br>
{{ league.id }}<br>
{{ league.name }}<br>
{{ league.num_teams }}<br>


<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <form action="{% url 'nba_fantasy:draft-settings' league.id %}" method="post">
                {% csrf_token %}
                {{ form }}<br>
                <input type="submit" value="Save Draft Settings"/>
            </form>

            <!--input type="text" class="form-control" placeholder="Server's hostname" id="server_name">
            <span-- class="input-group-btn">
                <button class="btn btn-default" type="button" id="add_server">Add</button>
            </span-->
        </div><!-- /input-group -->
    </div>
</div>

{% endblock %}

nba_fantasy/templates/nba_fantasy/edit_team.html
{% extends "nba_stats/base.html" %}
{% block title %} Edit Team {% endblock %}
{% block content %}

{{ league.name }}<br>
Edit Team<br>

<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <form action="{% url 'nba_fantasy:edit-team' league.id team.id%}" method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" value="Save Team"/>
            </form>

            <!--input type="text" class="form-control" placeholder="Server's hostname" id="server_name">
            <span-- class="input-group-btn">
                <button class="btn btn-default" type="button" id="add_server">Add</button>
            </span-->
        </div><!-- /input-group -->
    </div>
</div>

{% endblock %}

nba_fantasy/templates/nba_fantasy/free_agents.html
{% extends "nba_fantasy/league_base.html" %}
{% block title %} {{ league.name }} Free Agents{% endblock %}
{% block content %}

Free Agents<br>
{{ league.id }}<br>
{{ league.name }}<br>
{{ league.num_teams }}<br>

<table id="fa_players_table" class="table table-striped">
    <thead>
        <tr>
            <th>Player</th>
        </tr>
    </thead>
    <tbody>
        {% for player in fa_players %}
            <tr id="{{player.id}}_player_row">
                <td>{{ player.display_first_last }}</td>
                <td><button type="button" class="btn btn-default" id="{{player.id}}_button">Add</button></td>
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

{% block javascript %}
<script>
    $(".btn").click(function(e){
            console.log("Button clicked!");
            var id = $(this).attr("id").replace("_button", "");
            var player_id = parseInt(id);
            console.log(player_id);

            $.ajax({
                url: '/nba_fantasy/ajax/add_free_agent/',
                type: 'GET',
                data: {
                    'league_id': {{league.id}},
                    'fantasy_team_id': {{ team.id }},
                    'player_id': player_id
                },
                dataType: 'json',
                success: function(data){
                    if (data.added){
                        console.log("Added player!");
                        alert("Added player!");
                    }
                    else {
                        console.log("failed to add player!");
                        alert("failed to add player!");
                    }
                }
            });
        });
</script>
{% endblock %}

nba_fantasy/templates/nba_fantasy/index.html
{% extends 'nba_stats/base.html' %}
{% block title %}NBAPex | Fantasy Basketball{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-4">
            <div class="list-group">
                {% for team in my_teams %}
                    <a href="{% url 'nba_fantasy:view-team' team.id %}" class="list-group-item">{{ team.city }} {{ team.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

nba_fantasy/templates/nba_fantasy/league_base.html
{% extends "nba_stats/base.html" %}
{% block title %} {{league.name}}{% endblock %}
{% block subnav %}
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'nba_fantasy:league-homepage' league.id %}">League Home</a></li>
        <li role="presentation"><a href="{% url 'nba_fantasy:view-team' team_id %}">Team</a></li>
        <li role="presentation"><a href="{% url 'nba_fantasy:free-agents' league.id %}">Free Agents</a></li>
        <li role="presentation"><a href="{% url 'nba_fantasy:standings' league.id %}">Standings</a></li>
        <li role="presentation"><a href="{% url 'nba_fantasy:schedule' league.id %}">Matchups</a></li>
    </ul>
    <br>
{% endblock %}

nba_fantasy/templates/nba_fantasy/league_homepage.html
{% extends "nba_fantasy/league_base.html" %}

{% block title %} {{league.name}} Homepage {% endblock %}
{% block content %}

Welcome to your league

{% endblock %}

nba_fantasy/templates/nba_fantasy/login.html
{% extends "nba_stats/base.html" %}
{% block title %} Login to NBAPex Fantasy {% endblock %}
{% block content %}

<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <form action="{% url 'nba_fantasy:login' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" value="Login"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}

nba_fantasy/templates/nba_fantasy/roster_settings.html
{% extends "nba_stats/base.html" %}
{% block title %} Roster Settings {% endblock %}
{% block content %}
{{ league.id }}<br>
{{ league.name }}<br>
{{ league.num_teams }}<br>

<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <form action="{% url 'nba_fantasy:roster-settings'%}" method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" value="Save Roster Settings"/>
            </form>
            </span-->
        </div>
    </div>
</div>

{% endblock %}

nba_fantasy/templates/nba_fantasy/schedule.html
{% extends "nba_fantasy/league_base.html" %}
{% load filterqueryset %}
{% block title %}{{ league.name }}{% endblock %}

{% block content %}
    <h1>{{ league.name }} Schedule</h1>
    <div class="btn-group" role="group" aria-label="...">
        {% for week in weeks %}
            <button type="button" class="btn btn-default"
                    data-toggle="collapse" data-target="#week_{{ forloop.counter0 }}">{{ forloop.counter0 }}</button>
        {% endfor %}
    </div>
    {% for week in weeks %}
        <div id="week_{{ forloop.counter0 }}" class="collapse">
            <table class="table" >
                <thead>
                    <tr>
                       <th>Week</th>
                        <th>Away Team</th>
                        <th>Home Team</th>
                    </tr>
                </thead>
                <tbody>
                {% for matchup in week %}
                    <tr>
                        <td>
                            <a href="{% url 'nba_fantasy:matchup' matchup_id=matchup.id %}">
                                {{ matchup.week_num }}
                            </a>
                        </td>
                        <td>{{ matchup.away_team.city }} {{ matchup.away_team.name }}</td>
                        <td>{{ matchup.home_team.city }} {{ matchup.home_team.name }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endfor %}
{% endblock %}

{% block javascript %}
    <script>
        var curWeek = {{ cur_week }};
        console.log(curWeek);
        var curWeekDiv = $("#week_" + curWeek.toString());
        curWeekDiv.collapse("show");
    </script>
{% endblock %}

nba_fantasy/templates/nba_fantasy/schedule_settings.html
{% extends "nba_stats/base.html" %}
{% block title %} {{ league.name }} Schedule Settings {% endblock %}
{% block content %}

Schedule Settings<br>
{{ league.id }}<br>
{{ league.name }}<br>
{{ league.num_teams }}<br>


<div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <form action="{% url 'nba_fantasy:schedule-settings' %}" method="post">
                {% csrf_token %}
                {{ form }}<br>
                <input type="submit" value="Save Schedule Settings"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}

nba_fantasy/templates/nba_fantasy/standings.html
{% extends 'nba_fantasy/league_base.html' %}
{% block title %}{{ league.name }} | Standings{% endblock %}

{% block content %}
    <div id="standings_div">
        <table id="standings_table" class="table">
            <thead>
                <tr>
                    <th>Team</th>
                    <th>Wins</th>
                    <th>Losses</th>
                    <th>Ties</th>
                    <th>Win Pct</th>
                </tr>
            </thead>
            <tbody>
                {% for cur_team in team_standings %}
                    <tr>
                        <td><a href="{% url 'nba_fantasy:view-team' cur_team.id %}">{{ cur_team.city }} {{ cur_team.name }}</a></td>
                        <td>{{ cur_team.wins }}</td>
                        <td>{{ cur_team.losses }}</td>
                        <td>{{ cur_team.ties }}</td>
                        <td>{{ cur_team.win_pct }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}