NBAPex/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^nba_stats/', include('nba_stats.urls', namespace='nba_stats')),
    url(r'^nba_fantasy/', include('nba_fantasy.urls', namespace='nba_fantasy')),
]

nba_stats/urls.py
from django.conf.urls import url
from nba_stats import views, ajax_views

urlpatterns = [url(r'^$', views.index, name='index'),
               url(r'^admin_portal', views.admin_portal, name='admin_portal'),
               url(r'^players/$', views.players, name='players'),
               url(r'^player/(?P<id>[0-9]+)$', views.player, name='player'),
               url(r'^teams/$', views.teams, name='teams'),
               url(r'^team/(?P<id>[0-9]+)$', views.team, name='team'),
               url(r'^games/$', views.games, name='games'),
               url(r'^games/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
                   views.games, name='games-date'),
               url(r'^user_query/$', views.user_query, name='user-query'),
               url(r'^shot_chart/$', views.shot_chart, name='shot-chart'),
               url(r'^roster_history/$', views.roster_history, name='roster-history'),
               url(r'^download_user_query_results/(?P<fmt>[a-z]+)/$',
                   views.download_user_query_results, name="download-user-query-result"),
               # Begin AJAX calls
               url(r'^ajax/get_player_shot_chart_data/$', ajax_views.get_player_shot_chart_data,
                   name='get-player-shot-chart-data'),
               url(r'^ajax/get_team_roster_history/$', ajax_views.get_team_roster_history,
                   name='get-team-roster-history'),
               url(r'^ajax/get_related_models/$', ajax_views.ajax_get_related_models,
                   name="ajax-get-related-models"),
               url(r'^ajax/send_user_query/$', ajax_views.ajax_send_user_query,
                   name="ajax-send-user-query"),
               url(r'^ajax/get_player_splits/$', ajax_views.ajax_get_player_splits,
                   name="ajax-get-player-splits"),
               url(r'^ajax/get_team_splits/$', ajax_views.ajax_get_team_splits,
                   name="ajax-get-team-splits")
               ]

nba_stats/forms.py
from django import forms
from datetime import date
from nba_stats.utils import make_season_str

PLAYER_SPLIT_TYPE_CHOICES = [("Traditional", "Traditional"),
                             ("Advanced", "Advanced"),
                             ("Misc", "Misc"),
                             ("Shooting", "Shooting"),
                             ("Usage", "Usage"),
                             ("Scoring", "Scoring")]
SEASON_CHOICES = [(str(year), make_season_str(year)) for year in range(1996, date.today().year)]


class GameUpdateForm(forms.Form):
    begin_date = forms.DateField()
    end_date = forms.DateField()


class SplitSearchForm(forms.Form):
    season_id = forms.ChoiceField(SEASON_CHOICES, required=False)
    season_type = forms.CharField(max_length=50, required=False, initial="Regular Season")
    split_type = forms.ChoiceField(PLAYER_SPLIT_TYPE_CHOICES, required=False)
    per_mode = forms.CharField(max_length=50, required=False, initial="PerGame")
    order_by = forms.CharField(max_length=50, required=False)


class UserQueryForm(forms.Form):
    pass

nba_stats/views.py
import logging
import csv
import json
from collections import OrderedDict
from datetime import date
from uuid import uuid4
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from dicttoxml import dicttoxml
from nba_stats.models import (Player, PlayerTraditionalSplit,
                              PlayerAdvancedSplit, PlayerMiscSplit,
                              PlayerShootingSplit, PlayerUsageSplit,
                              PlayerScoringSplit, TeamTraditionalSplit,
                              TeamAdvancedSplit, TeamMiscSplit,
                              TeamShootingSplit, TeamScoringSplit,
                              Game, LineScore, PlayerSeason, Transaction,
                              Team, TeamSeason)
from nba_stats.utils import (convert_datetime_string_to_date_instance,
                             determine_season_for_date, make_season_str,
                             get_default_display_fields, get_field_literals,
                             get_user_exposed_models, get_user_exposed_model_fields)
from nba_stats.forms import GameUpdateForm, SplitSearchForm
from nba_stats.helpers.team import get_currently_active_teams, get_team_context
from nba_stats.helpers.game import get_display_data_for_line_score
from nba_stats.helpers.player import get_player_context

SPLIT_TYPE_MAP = {"PlayerTraditional": PlayerTraditionalSplit,
                  "PlayerAdvanced": PlayerAdvancedSplit,
                  "PlayerMisc": PlayerMiscSplit,
                  "PlayerShooting": PlayerShootingSplit,
                  "PlayerUsage": PlayerUsageSplit,
                  "PlayerScoring": PlayerScoringSplit,
                  "TeamTraditional": TeamTraditionalSplit,
                  "TeamAdvanced": TeamAdvancedSplit,
                  "TeamMisc": TeamMiscSplit,
                  "TeamShooting": TeamShootingSplit,
                  "TeamScoring": TeamScoringSplit}

log = logging.getLogger('stats')

DEFAULT_SPLIT_SEARCH = {'season_id': date.today().year,
                        'season_type': 'Regular Season',
                        'split_type': "Traditional",
                        'per_mode': "PerGame",
                        'group_set': "Overall"}


def index(request):
    context = {}
    return render(request, 'nba_stats/index.html', context)


def players(request):
    if request.GET:
        form = SplitSearchForm(request.GET)
        if form.is_valid():
            search = form.cleaned_data
            search['group_set'] = "Overall"
        else:
            log.debug("BORK")
            search = {}
    else:
        search = DEFAULT_SPLIT_SEARCH

        form = SplitSearchForm()

    model = SPLIT_TYPE_MAP["Player" + search['split_type']]
    log.debug(("ARAMDILLO", model))
    # TODO: Make all these field selections dynamically selectable for the user as well.
    fields = get_default_display_fields(model, exclude=["plus_minus", "dd2", "td3"])
    header_labels = ["Player"] + get_field_literals(fields)
    all_fields = ['player__display_first_last'] + fields
    order_by = search.get('order_by') or "-" + all_fields[-1]

    log.debug(("BADGER", search))

    raw_seasons = model.objects.filter(season_id=int(search['season_id']),
                                       season_type=search['season_type'],
                                       per_mode=search['per_mode'],
                                       group_set=search['group_set'])
    log.debug(("CHEETAH", raw_seasons.count()))
    id_list = raw_seasons.values_list('player__id', flat=True).order_by(order_by)
    seasons = raw_seasons.values_list(*all_fields).order_by(order_by)

    context = {'header_labels': header_labels, 'seasons': seasons,
               'form': form, 'id_list': id_list}
    return render(request, 'nba_stats/players.html', context)


def player(request, id):
    plr = Player.objects.get(id=id)
    last_transaction = Transaction.objects.filter(player=plr).order_by('-transaction_date').first()
    # TODO: This is a scenario where REST API may be helpful
    serialized = json.loads(serializers.serialize('json', [plr]))[0]
    player_json = serialized['fields']
    player_json['id'] = plr.id
    player_json = json.dumps(player_json)
    display_field_info = get_user_exposed_model_fields(PlayerSeason,
                                                       translation_style="upper",
                                                       exclude=["season_type", "team", "per_mode",
                                                                "player", "player_name",
                                                                "league_id"])
    season_headers = [info['display_value'] for info in display_field_info]
    fields = [info['field_name'] for info in display_field_info]
    context = get_player_context(plr, fields)
    context['headers'] = season_headers
    context['player_json'] = player_json
    context['last_transaction'] = last_transaction
    return render(request, "nba_stats/player.html", context)


def teams(request):
    if request.GET:
        form = SplitSearchForm(request.GET)
        if form.is_valid():
            search = form.cleaned_data
            search['group_set'] = "Overall"
        else:
            log.debug("BORK")
            search = {}
    else:
        search = DEFAULT_SPLIT_SEARCH

        form = SplitSearchForm()

    model = SPLIT_TYPE_MAP["Team" + search['split_type']]
    # TODO: Make all these field selections dynamically selectable for the user as well.
    fields = get_default_display_fields(model, exclude=["plus_minus", "dd2", "td3"])
    header_labels = ["Team"] + get_field_literals(fields)
    all_fields = ['team__abbreviation'] + fields
    order_by = search.get('order_by') or "-" + all_fields[-1]

    raw_seasons = model.objects.filter(season_id=int(search['season_id']),
                                       season_type=search['season_type'],
                                       per_mode=search['per_mode'],
                                       group_set=search['group_set'])
    id_list = raw_seasons.values_list('team__id', flat=True).order_by(order_by)
    seasons = raw_seasons.values_list(*all_fields).order_by(order_by)
    context = {'header_labels': header_labels,
               'seasons': seasons, 'form': form,
               'id_list': id_list}
    return render(request, 'nba_stats/teams.html', context)


def team(request, id):
    requested_team = Team.objects.get(id=id)
    serialized = json.loads(serializers.serialize('json', [requested_team]))[0]
    team_json = serialized['fields']
    team_json['id'] = requested_team.id
    team_json['from_year'] = 1996
    team_json['to_year'] = 2016
    team_json = json.dumps(team_json)
    display_field_info = get_user_exposed_model_fields(TeamSeason,
                                                       translation_style="upper",
                                                       exclude=["season_type", "team", "per_mode",
                                                                "league_id", "team_abbreviation",
                                                                "team_city", "team_name",
                                                                "conf_count", "div_count"])
    season_headers = [info['display_value'] for info in display_field_info]
    fields = [info['field_name'] for info in display_field_info]
    log.debug(("FIELDS", fields))
    context = {'team': requested_team,
               'headers': season_headers,
               'team_json': team_json}

    context.update(get_team_context(requested_team, fields))
    return render(request, 'nba_stats/team.html', context)


def games(request, year=None, month=None, day=None):
    if any([year, month, day]) and not all([year, month, day]):
        log.debug("I'm not sure how the hell we got here, but things are all borked up.")
        log.debug(("year, month, day ", year, month, day))
        raise Exception("Bork")
    elif not any([year, month, day]):
        the_date = date.today()
    else:
        the_date = date(year=int(year), month=int(month), day=int(day))

    todays_games = Game.objects.filter(game_date_est=the_date)
    line_scores = LineScore.objects.filter(game__in=todays_games)
    ls_dict = {ls.team.id: get_display_data_for_line_score(ls) for ls in line_scores}
    context = {'games': todays_games, 'line_scores': ls_dict}
    return render(request, 'nba_stats/games.html', context)


def admin_portal(request):
    if request.method == "POST":
        form = GameUpdateForm(request.POST)
        if form.is_valid():
            log.debug(request.POST)
            begin_date_str = request.POST['begin_date']
            end_date_str = request.POST['end_date']
            begin_date = convert_datetime_string_to_date_instance(begin_date_str)
            end_date = convert_datetime_string_to_date_instance(end_date_str)
            log.debug(("Dates", begin_date, end_date))
            return HttpResponseRedirect("")
    else:
        form = GameUpdateForm()

    context = {'form': form}
    return render(request, "nba_stats/admin_portal.html", context)


def shot_chart(request):
    active_players = Player.active_players.all()
    cur_year = determine_season_for_date(date.today())
    seasons = {}
    for year in range(2001, cur_year + 1):
        seasons[year] = make_season_str(year)
    context = {'players': active_players, 'seasons': seasons}
    return render(request, "nba_stats/shot_chart.html", context)


def roster_history(request):
    active_teams = get_currently_active_teams()
    context = {'teams': active_teams}
    return render(request, "nba_stats/roster_history.html", context)


def user_query(request):
    exposed_models = [model.__name__ for model in get_user_exposed_models()]
    context = {'models': exposed_models}
    return render(request, 'nba_stats/user_query.html', context)


def download_user_query_results(request, fmt):

nba_stats/templates/nba_stats/admin_portal.html
{% extends "nba_stats/base.html" %}

{% block content %}
<div class="row">
        <div class="col-lg-6">
            <div class="input-group">
                <form action="{% url 'nba_stats:admin_portal' %}" method="post">
                    {% csrf_token %}
                    {{ form }}<br>
                    <input type="submit" value="Go!"/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

nba_stats/templates/nba_stats/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}NBAPex{% endblock %}</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  </head>
  <body id="body">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'nba_stats:index' %}">NBAPex</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="nbapex-navbar">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="{% url 'nba_stats:index' %}" class="dropdown-toggle"
                 data-toggle="dropdown" role="button"
                 aria-haspopup="true" aria-expanded="false">Stats<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'nba_stats:players' %}">Players</a></li>
                <li><a href="{% url 'nba_stats:teams' %}">Teams</a></li>
                <li><a href="{% url 'nba_stats:games' %}">Games</a></li>
                <li><a href="{% url 'nba_stats:shot-chart' %}">Shot Charts</a></li>
                <li><a href="{% url 'nba_stats:roster-history' %}">Roster History</a></li>
                  <li><a href="{% url 'nba_stats:user-query' %}">User Query</a></li>
              </ul>
            </li>
            <li><a href="{% url 'nba_fantasy:index' %}">Fantasy</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="col-lg-12">
        {% block subnav %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
    {% block javascript %}{% endblock %}
  </body>
</html>

nba_stats/templates/nba_stats/games.html
{% extends 'nba_stats/base.html' %}
{% load getattribute %}


{% block title %} Games {% endblock %}

{% block content %}
<!-- I've put a fair amount of logic in this file. Not sure if I like it, but it's all UI related. -->

{% for game in games %}
    <div id="div_{{ game.id }}" class="col-md-8">
        <table id="table_{{ game.id }}" class="table">
            <thead>
                <tr>
                    <th></th>
                    {% with line_score=line_scores|getattribute:game.visitor_team.id %}
                        {% for period in line_score %}
                            {% if forloop.last %}
                                <th>Final</th>
                            {% elif forloop.counter < 5 %}
                                <th>Q{{ forloop.counter }}</th>
                            {% else %}
                                <th>OT{{ forloop.counter|add:"-4" }}</th>
                            {% endif %}
                        {% endfor %}
                    {% endwith %}
                </tr>
            </thead>
            <tr>
                {% with line_score=line_scores|getattribute:game.visitor_team.id %}
                    <td>{{ game.visitor_team.city }} {{ game.visitor_team.name }}</td>
                    {% for val in line_score %}
                        <td>{{ val }}</td>
                    {% endfor %}
                {% endwith %}
            </tr>
            <tr>
                {% with line_score=line_scores|getattribute:game.home_team.id %}
                    <td>{{ game.home_team.city }} {{ game.home_team.name }}</td>
                    {% for val in line_score %}
                        <td>{{ val }}</td>
                    {% endfor %}
                {% endwith %}
            </tr>
            <tr>
                <td colspan="2">{{ game.live_period_time_bcast }}</td>
                <td colspan="2"> Attendance: {{ game.attendance }}</td>
                <td colspan="2"> Duration: {{ game.game_time }}</td>
            </tr>
        </table>
    </div>
{% endfor %}

{% endblock %}

nba_stats/templates/nba_stats/index.html
{% extends 'nba_stats/base.html' %}

{% block title %}NBAPex Stats{% endblock %}

{% block content %}
Welcome to the home page. Not sure what to put here
{% endblock %}

nba_stats/templates/nba_stats/players.html
{% extends 'nba_stats/base.html' %}
{% load getattribute %}
{% block title %}Players{% endblock %}
{% block content %}
<div class="col-lg-6">
    <div class="input-group">
        <form action="{% url 'nba_stats:players' %}" method="get">
            {{ form.as_p }}
            <input type="submit" value="Get"/>
        </form>
    </div>
</div><br/>
<table class="table table-hover table-bordered table-responsive">
    <thead>
        <tr>
            {% for label in header_labels %}
                <th>{{ label }}</th>
            {% endfor%}
        </tr>
    </thead>
    <tbody>
        {% for season in seasons %}
            {% with idx=forloop.counter0 %}
                <tr>
                    {% for val in season %}
                        <td>
                        {% if forloop.counter0 == 0 %}
                            <a href="{% url 'nba_stats:player' id_list|getattribute:idx %}">
                                {{ val }}
                            </a>
                        {% else %}
                            {{ val }}
                        {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endwith %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

nba_stats/templates/nba_stats/roster_history.html
{% extends 'nba_stats/base.html' %}
{% load static %}
{% block title %}NBAPex Roster History{% endblock %}

{% block content %}
    <script src={% static 'moment/js/moment.js' %}></script>
    <link href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}" rel="stylesheet">
    <script src={% static 'bootstrap-datepicker/js/bootstrap-datepicker.js' %}></script>
    <link href="{% static 'bootstrap-combobox/css/bootstrap-combobox.css' %}" rel="stylesheet">
    <script src={% static 'bootstrap-combobox/js/bootstrap-combobox.js' %}></script>
    <script src={% static 'd3/d3.min.js' %}></script>
    <style>
        .links line {
          stroke: #999;
          stroke-opacity: 0.6;
        }
        .nodes circle {
          stroke: #fff;
          stroke-width: 1.5px;
        }

    </style>
    <!-- For whatever reason, this isn't quite working right. It's not styled.-->
    <div id="roster-date-div" class="input-group date">
        <input id="roster-date" type="text" class="form-control">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-th"></i>
            </span>
    </div>
    <div id="team-div">
        <select id="teams" class="combobox">
            <option></option>
            {% for team in teams %}
                <option value="{{ team.id }}">{{ team.city }} {{ team.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div>
        <button type="button" class="btn btn-default" id="get_roster_button">Go</button>
    </div>
    <svg width="960" height="600"></svg>
    <div id="roster_table_div"></div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'nba_stats/js/roster_history.js' %}"></script>
{% endblock %}

nba_stats/templates/nba_stats/shot_chart.html
{% extends "nba_stats/base.html" %}
{% load static %}
{% load getattribute %}
{% block title %}NBAPex Shot Chart Viewer{% endblock %}
{% block content %}
    <!-- Might move this to base.html at some point, but as of now it's not needed there -->
    <script src={% static 'd3/d3.min.js' %}></script>
    <link href="{% static 'bootstrap-combobox/css/bootstrap-combobox.css' %}" rel="stylesheet">
    <script src={% static 'bootstrap-combobox/js/bootstrap-combobox.js' %}></script>
    <link href="{% static 'slider/css/slider.css' %}" rel="stylesheet">
    <script src="{% static 'slider/js/bootstrap-slider.js' %}"></script>

    <style>
        body {
          font: 11px sans-serif;
        }

        .axis path,
        .axis line {
          fill: none;
          stroke: #000;
          shape-rendering: crispEdges;
        }

        .dot {
          stroke: #000;
        }

        .tooltip {
          position: absolute;
          width: 200px;
          height: 28px;
          pointer-events: none;
        }
    </style>
    <div class="col-md-12">
        <div class="col-lg-6">
            <select id="players" class="combobox">
                <option></option>
                {% for player in players %}
                    <option value="{{ player.id }}">{{ player.display_first_last }}</option>
                {% endfor %}
            </select>
            <select id="seasons" class="combobox">
                <option></option>
                {% for year in seasons %}
                    <option value={{ year }}>{{ seasons|getattribute:year }}</option>
                {% endfor %}
            </select>
            <button type="button" class="btn btn-default" id="fetch_data_button">Go</button>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'nba_stats/js/shot_chart.js' %}"></script>
{% endblock %}

nba_stats/templates/nba_stats/sortable_player_stats.html
{% load getattribute %}

<h3>This is the sortable player stats page</h3>
{% if seasons %}
	<table id="player_seasons" border="1">
		{% if header_fields %}
			<tr>
				{% for header in header_fields %}
					<th>{{ header }}</th>
				{% endfor %}
			</tr>
			{% for season in seasons %}
				<tr>
					{% for field in model_fields %}
						{% if field == 'player' %}
							<td> <a href="{% url 'nba_stats:player' player_id=season.player.id %}">{{season.player.display_first_last }}</a></td>
						{% elif field == 'team' %}
							<!-- Apparently td align is not support in HTML5. TODO: Start using CSS...-->
							<td align="center"><a href="{% url 'nba_stats:team' team_id=season.team.id %}">{{ season.team.team_abbreviation }}</a></td>
						{% else %}
							<td align="center">{{ season|getattribute:field}}</td>
						{% endif %}
					{% endfor %}
				</tr>
			{% endfor %}
		{% endif %}
	</table>
{% endif %}

nba_stats/templates/nba_stats/teams.html
{% extends 'nba_stats/base.html' %}
{% load static %}
{% load getattribute %}
{% block title %}Teams{% endblock %}
{% block content %}
<div class="col-lg-6">
    <div class="input-group">
        <form action="{% url 'nba_stats:teams' %}" method="get">
            {{ form.as_p }}
            <input type="submit" value="Get"/>
        </form>
    </div>
</div><br/>
<table class="table table-hover table-bordered table-responsive">
    <thead>
        <tr>
            {% for label in header_labels %}
                <th>{{ label }}</th>
            {% endfor%}
        </tr>
    </thead>
    <tbody>
        {% for season in seasons %}
            {% with idx=forloop.counter0 %}
                <tr>
                    {% for val in season %}
                        <td>
                        {% if forloop.counter0 == 0 %}
                            <a href="{% url 'nba_stats:team' id_list|getattribute:idx %}">
                                {{ val }}
                            </a>
                        {% else %}
                            {{ val }}
                        {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endwith %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

nba_stats/templates/nba_stats/user_query.html
{% extends 'nba_stats/base.html' %}
{% load static %}
{% load getattribute %}
{% load translatefield %}

{% block title %} BYOQ {% endblock %}
{% block content %}
    <script src={% static 'd3/d3.js' %}></script>
    <style>

        .links line {
        stroke: #999;
        stroke-opacity: 0.6;
        }

        .nodes circle {
        stroke: #fff;
        stroke-width: 1.5px;
        }

    </style>
    <form id="user_query_form">
        <div id="model_div" class="col-md-4">
            <h3>Tables</h3>
            <select id="model" class="form-control" onchange="setFieldsDropdown();">
                <option></option>
                {% for model in models %}
                    <option class="model-option" value="{{ model }}">{{ model }}</option>
                {% endfor %}
            </select>
            <button type="button" class="btn btn-default" id="send_user_query">Go</button>
        </div>
        <div id="all_filters_div" class="col-md-4">
            <h3>Filters</h3>
            <button type="button" class="btn btn-default" id="add_filter_button">Add Filter</button>
        </div>
        <div id="all_fields_div" class="col-md-4">
            <h3>Selected Fields</h3>
        </div>
    </form>
    <svg width="960" height="600"></svg>
    <div id="results_div" class="col-md-12"></div>
{% endblock %}

{%  block javascript %}
    <script src="{% static 'nba_stats/js/user_query.js' %}"></script>
{% endblock %}